#!/usr/bin/env bash

### [ACTION: HELP] ################################################
#   Description:  Open help text in less.
#   Parameters:   None

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################



####



less /usr/local/bin/gorpmc/help.txt