#!/usr/bin/env bash

### [ACTION: GORP UPGRADE] ########################################
#   Description:  Upgrade Gorp.
#   Parameters:   None

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################



#### GUARDS ################

### KEY GUARD

if [[ "$1" == "pleasedontdothis" ]]; then
    OUTPUT=true
    ERRORS=true

elif [[ "$1" == "pleaseshutup" ]]; then
    OUTPUT=false
    ERRORS=true

elif [[ "$1" == "pleasebesilent" ]]; then
    OUTPUT=false
    ERRORS=false

else
    if $ERRORS; then echo "gorpupgrade: Not intended to be run directly. Exit (13)."; fi
    exit 13
fi







#### SCRIPT PARAMETERS ################

source /usr/local/bin/gorpmc/worker/i_getconfigparams.sh

I_VERSION=$(gorp -v | cut -d ' ' -f3)







####







### TEMP DIRECTORY

rm -rf $HOMEDIR/tmp/
mkdir -p $HOMEDIR/tmp/







### GET & STORE RELEASE INFORMATION

cd $HOMEDIR/tmp/
wget -q https://raw.githubusercontent.com/LanceNickel/Gorp/main/release



# Store

R_SHA256=$(grep 'SHA256=' release | cut -d '=' -f2)
R_MD5=$(grep 'MD5=' release | cut -d '=' -f2)
R_VERSION=$(grep 'V=' release | cut -d '=' -f2)








### DO WE EVEN NEED TO UPGRADE?

if [[ "$I_VERSION" == "$R_VERSION" ]]; then
    if $OUTPUT; then echo "Gorp is already on the latest version."; fi
    exit 0
fi







### GET SUDO PERMISSIONS RT-GUARD

if $OUTPUT; then echo "To upgrade, Gorp will use sudo."; fi
sudo whoami > /dev/null







### DOWNLOAD THE LATEST RELEASE

if $OUTPUT; then echo "Downloading latest release..."; fi

cd $HOMEDIR/tmp/
wget -q https://gorp.lanickel.com/release.tar.gz



# Checksums

L_SHA256=$(sha256sum release.tar.gz)
L_MD5=$(md5sum release.tar.gz)



# sha256 comparison

if [[ "$L_SHA256" != "$R_SHA256" ]]; then
    if $ERRORS; then echo "Downloaded checksum does not match remote (sha256)."
    exit 1
fi



# md5 comparison

if [[ "$L_MD5" != "$R_MD5" ]]; then
    if $ERRORS; then echo "Downloaded checksum does not match remote (md5)."
    exit 1
fi







### UNPACK TAR

tar -xf latest.tar.gz > /dev/null

mv ./latest ./updatefiles






exit







### RUN UPDATE WORKER

chmod +x $HOMEDIR/tmp/updatefiles/upgrade.sh
$HOMEDIR/tmp/updatefiles/upgrade.sh $1







### CLEAN UP

rm -rf $HOMEDIR/tmp/