#!/usr/bin/env bash

### [GORPUPDATE] ##################################################
#   Description:  Action script to setup Gorp update worker.
#   Parameters:   None

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################



# PERMISSIONS GUARD

if [[ "$EUID" != 0 ]]; then
    echo "GORP UPDATE: Insufficient privilege. Update failed."
    exit
fi



####



# TEMP DIRECTORY

rm -rf /minecraft/tmp
mkdir /minecraft/tmp



# GIT CLONE LATEST C.U.M. FILES

echo "GORP UPDATE: Downloading newest scripts..."

git clone --quiet https://github.com/LanceNickel/mc-cum /minecraft/tmp/updatefiles



# RUN UPDATE WORKER

chmod +x /minecraft/tmp/updatefiles/update.sh
/minecraft/tmp/updatefiles/update.sh



# CLEAN UP

rm -rf /minecraft/tmp