#!/usr/bin/env bash

### [ACTION: MOVE-HOME] ###########################################
#   Description:  Move $HOMEDIR to new location.
#   Parameters:   (required) Absolute path to new home directory

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################

# Copyright (C) Lance Nickel 2023.
# Distributed under GNU GPL v3.
# <https://gorp.lanickel.com/license/>



#### GUARDS ################

### KEY GUARD

if [[ "$1" == "pleasedontdothis" ]]; then
    handle_error "Script not meant to be run directly"
fi







#### SCRIPT PARAMETERS ################

NEW_HOMEDIR=$2







####







### GET SUDO PERMISSIONS RT-GUARD

echo "Gorp will use sudo to update the configuration file"
sudo whoami > /dev/null || handle_error "Failed to get sudo privileges"







### DOES DESTINATION EXIST/IS IT EMPTY? RT-GUARD

if [[ -d $NEW_HOMEDIR ]]; then
    handle_error "This directory already exists"
fi







### ARE ANY SERVERS RUNNING? RT-GUARD

for d in "$HOMEDIR/servers/"*
do
        SERVER=$(basename "$d")
        
        if [[ $(gorp -s $SERVER | jq .status[].running) == "true" ]]; then
            handle_error "Servers cannot be running. Shut down all servers and try again"
        fi
done







### CALL THE WORKER

source /usr/local/bin/gorpmc/worker/movehome.sh $1 $NEW_HOMEDIR || handle_error "Unable to launch movehome.sh worker"