#!/usr/bin/env bash

### [ACTION: HELP] ################################################
#   Description:  Open help text in less.
#   Parameters:   None

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################

# Copyright (C) Lance Nickel 2025.
# Distributed under GNU GPL v3.
# <https://gorp.lanickel.com/license/>



####



less /usr/local/bin/gorpmc/help.txt || handle_error "Unable to open help text."
