#!/usr/bin/env bash

### [ACTION: BACKUP-WORLD] ########################################
#   Description:  Backup server files to $BACKUP_DEST
#   Parameters:   1: (required) Server directory name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################

# Copyright (C) Lance Nickel 2023.
# Distributed under GNU GPL v3.
# <https://gorp.lanickel.com/license/>



#### GUARDS ################

### KEY GUARD

if [[ "$1" == "pleasedontdothis" ]]; then
    OUTPUT=true
    ERRORS=true

elif [[ "$1" == "pleaseshutup" ]]; then
    OUTPUT=false
    ERRORS=true

elif [[ "$1" == "pleasebesilent" ]]; then
    OUTPUT=false
    ERRORS=false

else
    if $ERRORS; then echo "mcbackupworld: Not intended to be run directly. Exit (13)."; fi
    exit 13
fi







#### SCRIPT PARAMETERS ################

source /usr/local/bin/gorpmc/worker/i_getconfigparams.sh

SERVER=$2







####







### PARAM RT-GUARD

if [[ "$SERVER" == "" ]]; then
    if $ERRORS; then echo "mcbackupworld: Bad input. Expected: gorp backup-world [server-name]. Exit (14)."; fi
    exit 14
fi







### SERVER DIRECTORY RT-GUARD

if [[ -d "$HOMEDIR/servers/$SERVER" ]]; then
    # we can continue
    sleep 0.005
else
    if $ERRORS; then echo "mcbackupworld: Server not found. Exit (30)."; fi
    exit 30
fi







### NO WORLDS RT-GUARD

if [[ $(ls $HOMEDIR/servers/$SERVER/ | grep 'world') == "" ]]; then
    if $ERRORS; then echo -e "mcbackupworld: No worlds exist on this server. Exit (42)."; fi
    exit 42
fi







### RUN BACKUP WORKER

/usr/local/bin/gorpmc/worker/backupworld.sh $1 $SERVER