#!/usr/bin/env bash

### [ACTION: BACKUP-SERVER] #######################################
#   Description:  Backup server files to $BACKUP_DEST
#   Parameters:   1: (required) Server directory name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################



#### GUARDS ################

### KEY GUARD

if [[ "$1" == "pleasedontdothis" ]]; then
    OUTPUT=true
    ERRORS=true

elif [[ "$1" == "pleaseshutup" ]]; then
    OUTPUT=false
    ERRORS=true

elif [[ "$1" == "pleasebesilent" ]]; then
    OUTPUT=false
    ERRORS=false

else
    if $ERRORS; then echo "mcbackupserver: Not intended to be run directly. Exit (13)."; fi
    exit 13
fi







#### SCRIPT PARAMETERS ################

source /usr/local/bin/gorpmc/worker/i_getconfigparams.sh

SERVER=$2







####







### PARAM RT-GUARD

if [[ "$SERVER" == "" ]]; then
    if $ERRORS; then echo "mcbackupserver: Bad input. Expected: gorp backup-server [server-name]. Exit (14)."; fi
    exit 14
fi







### SERVER DIRECTORY RT-GUARD

if [[ -d "$HOMEDIR/servers/$SERVER" ]]; then
    # we can continue
    sleep 0.005
else
    if $ERRORS; then echo "mcbackupserver: Server not found. Exit (30)."; fi
    exit 30
fi







### SCREEN RT-GUARD

if [[ $(screen -ls | grep "$SERVER") != "" ]]; then
        if $ERRORS; then echo "mcbackupserver: Server cannot be running. Exit (34)."; fi
        exit 34
fi







### RUN BACKUP WORKER

/usr/local/bin/gorpmc/worker/backupserver.sh $1 $SERVER