#!/usr/bin/env bash

### [ACTION: BACKUP-SERVER] #######################################
#   Description:  Backup server files to $BACKUP_DEST
#   Parameters:   1: (required) Server directory name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################

# Copyright (C) Lance Nickel 2023.
# Distributed under GNU GPL v3.
# <https://gorp.lanickel.com/license/>



#### GUARDS ################

### KEY GUARD

if [[ "$1" == "pleasedontdothis" ]]; then
    handle_error "Script not meant to be run directly."
fi







#### SCRIPT PARAMETERS ################

SERVER=$2







####







### PARAM RT-GUARD

if [[ "$SERVER" == "" ]]; then
    if $ERRORS; then echo "mcbackupserver: Bad input. Expected: gorp backup-server [server-name]. Exit (14)."; fi
    exit 14
fi







### SERVER DIRECTORY RT-GUARD

if [[ -d "$HOMEDIR/servers/$SERVER" ]]; then
    # we can continue
    sleep 0.005
else
    if $ERRORS; then echo "mcbackupserver: Server not found. Exit (30)."; fi
    exit 30
fi







### SCREEN RT-GUARD

if [[ $(screen -ls | grep "$SERVER") != "" ]]; then
        if $ERRORS; then echo "mcbackupserver: Server cannot be running. Exit (34)."; fi
        exit 34
fi







### RUN BACKUP WORKER

/usr/local/bin/gorpmc/worker/backupserver.sh $1 $SERVER