#!/usr/bin/env bash

### [MCBACKUP] ####################################################
#   Description:  Action script to setup backup worker.
#   Parameters:   1: (required) Server directory name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################



# PERMISSIONS GUARD

if [[ "$EUID" != 0 ]]; then
        echo "BACKUP: Insufficient privilege. Backup failed."
        exit
fi



# SCRIPT VARIABLES

SERVER=$1



####



# PARAM GUARD

if [ "$SERVER" = "" ]; then
    echo "BACKUP: Please specify a server."
    exit
fi



# SERVER DIRECTORY GUARD

if [ -d "/minecraft/servers/$SERVER" ]; then
    # we can continue
    sleep 0.005
else
    echo "BACKUP: Specified server doesn't exist. Backup failed."
    exit
fi



# RUN BACKUP WORKER

/bin/gorputils/worker/backup.sh $SERVER