#!/usr/bin/env bash

### [ACTION: CREATE-WORLD] ########################################
#   Description:  Generate a new world in a server instance.
#   Parameters:   1: (required) Server directory name
#                 2: (optional*) World (level) name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################

# Copyright (C) Lance Nickel 2023.
# Distributed under GNU GPL v3.
# <https://gorp.lanickel.com/license/>



#### GUARDS ################

### KEY GUARD

if [[ "$1" == "pleasedontdothis" ]]; then
    handle_error "Script not meant to be run directly"
fi







#### SCRIPT PARAMETERS ################

SERVER=$2
NEW_WORLD=$3







####







# PARAM RT-GUARD

if [[ "$SERVER" == "" ]]; then
    handle_error "Bad input. Expected: gorp create-world [server-name] <world-name>"
fi







# SERVER DIRECTORY RT-GUARD

if [[ -d "$HOMEDIR/servers/$SERVER" ]]; then
    sleep 0.05
else
    handle_error "Server not found"
fi







# WORLD DIRECTORY RT-GUARD (when world name passed as param)

if [[ "$NEW_WORLD" != "" ]]; then

    if [[ -d "$HOMEDIR/servers/$SERVER/world-$NEW_WORLD" ]]; then
        handle_error "World already exists"
    fi

fi







# SCREEN RT-GUARD

if [[ $(screen -ls | grep "$SERVER") != "" ]]; then
        handle_error "Server cannot be running"
fi







# RUN THE WORLD CREATOR WORKER

source /usr/local/bin/gorpmc/worker/createworld.sh $1 $SERVER $NEW_WORLD || handle_error "Failed to run createworld.sh worker"