#!/usr/bin/env bash

### [ACTION: CREATE-SERVER] #######################################
#   Description:  Create a new server instance.
#   Parameters:   1: (required) Server directory name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################

# Copyright (C) Lance Nickel 2025.
# Distributed under GNU GPL v3.
# <https://gorp.lanickel.com/license/>



#### SETUP ############

#### Globals

. /usr/local/bin/gorpmc/functions/exit.sh
. /usr/local/bin/gorpmc/functions/params.sh
. /usr/local/bin/gorpmc/functions/functions.sh



#### Key guard

if [[ "$1" != "pleasedontdothis" ]]; then
    handle_error "Script not meant to be run directly."
fi



#### Collect arguments & additional variables

SERVER=$2
ARG1=$3
ARG2=$4



#### Handle positional world name and velocity arguments

# User gave a world name and "velocity"
if [[ "$ARG2" == "velocity" ]]; then
    WORLD="$ARG1"
    VELOCITY="true"

# User gave "velocity" but did not specify a world name (velocity is back one position)
elif [[ "$ARG1" == "velocity" ]] && [[ "$ARG2" == "" ]]; then
    WORLD="default"
    VELOCITY="true"

# User gave a world name but did not specify "velocity" (normal creation w/o velocity)
elif [[ "$ARG1" != "" ]]; then
    WORLD="$ARG1"
    VELOCITY="false"

# User gave no world name or velocity
elif [[ "$ARG1" == "" ]]; then
    WORLD="default"
    VELOCITY="false"

fi







####







#### GUARDS ############

#### Bad user input

if [[ "$SERVER" == "" ]]; then
    handle_error "Bad input. Expected: gorp create-server [server-name] <world-name> <velocity>."
fi



#### Server already exists

if [[ "$(does_server_exist $SERVER)" == "true" ]]; then
    handle_error "Server already exists."
fi



#### Illegal server names

if [[ "$SERVER" == "--all" ]] || [[ "$SERVER" == "-all" ]] || [[ "$SERVER" == "all" ]]; then
    handle_error "Invalid server name, try another."
fi







#### MINECRAFT EULA ############

echo -e "\n==== IMPORTANT! ====\nTo continue you must agree to the Minecraft EULA (https://aka.ms/MinecraftEULA)."

read -r -p "Do you agree to the Minecraft EULA? [y/N]: " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    sleep 0.25
else
    handle_error "You must agree to the Minecraft EULA! Read it: https://aka.ms/MinecraftEULA"
fi







#### RUN THE CREATOR WORKER ############

bash /usr/local/bin/gorpmc/worker/createserver.sh $1 $SERVER $WORLD $VELOCITY || handle_error "Failed to run createserver.sh worker."
