#!/usr/bin/env bash

### [MCCREATESERVER] ##############################################
#   Description:  Action script to setup server creator worker.
#   Parameters:   1: (required) Server directory name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################



# PERMISSIONS GUARD

if [[ "$EUID" != 0 ]]; then
    echo "mccreate: Insufficient privilege. Exiting."
    exit
fi



# SCRIPT VARIABLES

SERVER=$1



####



# PARAM GUARD

if [ "$SERVER" = "" ]; then
    echo "mccreate: Please specify a server name to create. Exiting."
    exit
fi



# SERVER DIRECTORY GUARD

if [ -d "/minecraft/servers/$SERVER" ]; then
    echo "mccreate: Specified server already exists. Exiting."
    exit
fi



# USER EULA AND AGREEMENT GUARD

echo -e "\n==== IMPORTANT! ====\nTo continue you must agree to the Minecraft EULA (https://aka.ms/MinecraftEULA).\nYou must also agree to use Gorp for PERSONAL USE ONLY."

read -r -p "Do you agree to the Minecraft EULA? [y/n]: " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    sleep 0.25
else
    echo "You did not agree to the Minecraft EULA. Exiting."
    exit
fi

read -r -p "Do you agree to use Gorp for personal use only? COMMERCIAL USE PROHIBITED. [y/n]: " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    sleep 0.25
else
    echo "Gorp is for personal use. If you are an interested commercial entity, please reach out to gorp@lanickel.com"
    exit
fi




# RUN THE CREATOR WORKER

/bin/gorputils/worker/createserver.sh $SERVER