#!/usr/bin/env bash

### [ACTION: CREATE-SERVER] #######################################
#   Description:  Create a new server instance.
#   Parameters:   1: (required) Server directory name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################



#### GUARDS ################

### KEY GUARD

if [[ "$1" == "pleasedontdothis" ]]; then
    OUTPUT=true
    ERRORS=true

elif [[ "$1" == "pleaseshutup" ]]; then
    OUTPUT=false
    ERRORS=true

elif [[ "$1" == "pleasebesilent" ]]; then
    OUTPUT=false
    ERRORS=false

else
    if $ERRORS; then echo "mccreateserver: Not intended to be run directly. Exit (13)."; fi
    exit 13
fi








#### SCRIPT PARAMETERS ################

source /usr/local/bin/gorpmc/worker/i_getconfigparams.sh

SERVER=$2

# World name override

if [[ "$3" == "" ]]; then
    WORLD="default"
else
    WORLD=$3
fi







####







### PARAM RT-GUARD

if [[ "$SERVER" == "" ]]; then
    if $ERRORS; then echo "mccreateserver: Bad input. Expected: gorp create-server [server-name] <world-name>. Exit (14)."; fi
    exit 14
fi







### SERVER DIRECTORY RT-GUARD

if [[ -d "$HOMEDIR/servers/$SERVER" ]]; then
    if $ERRORS; then echo "mccreateserver: Server already exists. Exit (31)."; fi
    exit 31
fi







### USER EULA AND AGREEMENT RT-GUARD

if $OUTPUT; then echo -e "\n==== IMPORTANT! ====\nTo continue you must agree to the Minecraft EULA (https://aka.ms/MinecraftEULA).\nYou must also agree to use Gorp for PERSONAL USE ONLY."; fi

read -r -p "Do you agree to the Minecraft EULA? [y/n]: " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    sleep 0.25
else
    if $ERRORS; then echo "You must agree to the EULA and Gorp terms. Exit (12)."; fi
    exit 12
fi

read -r -p "Do you agree to use Gorp for personal use only? COMMERCIAL USE PROHIBITED. [y/n]: " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    sleep 0.25
else
    if $ERRORS; then echo "mccreateserver: You must agree to the EULA and Gorp terms. Exit (12)."; fi
    exit 12
fi








### RUN THE CREATOR WORKER

/usr/local/bin/gorpmc/worker/createserver.sh $1 $SERVER $WORLD
