#!/usr/bin/env bash

### [MCCREATE] ####################################################
#   Description:  Action script to setup server creator worker.
#   Parameters:   1: (required) Server directory name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################



# PERMISSIONS GUARD

if [[ "$EUID" != 0 ]]; then
    echo "mccreate: Insufficient privilege. Exiting."
    exit
fi



# SCRIPT VARIABLES

SERVER=$1



####



# PARAM GUARD

if [ "$SERVER" = "" ]; then
    echo "mccreate: Please specify a server name to create. Exiting."
    exit
fi



# SERVER DIRECTORY GUARD

if [ -d "/minecraft/servers/$SERVER" ]; then
    echo "mccreate: Specified server already exists. Exiting."
    exit
fi



# RUN THE CREATOR WORKER

/bin/gorputils/worker/create.sh $SERVER