#!/usr/bin/env bash

### [ACTION: CREATE-WORLD] ########################################
#   Description:  Generate a new world in a server instance.
#   Parameters:   1: (required) Server directory name
#                 2: (optional*) World (level) name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################

# Copyright (C) Lance Nickel 2023.
# Distributed under GNU GPL v3.
# <https://gorp.lanickel.com/license/>



#### SETUP ############

#### Globals

source /usr/local/bin/gorpmc/functions/exit.sh
source /usr/local/bin/gorpmc/functions/params.sh
source /usr/local/bin/gorpmc/functions/functions.sh



#### Key guard

if [[ "$1" != "pleasedontdothis" ]]; then
    handle_error "Script not meant to be run directly."
fi



#### Collect arguments & additional variables

SERVER=$2
NEW_WORLD=$3







####







#### GUARDS ############

#### Bad user input

if [[ "$SERVER" == "" ]]; then
    handle_error "Bad input. Expected: gorp create-world [server-name] <world-name>."
fi



#### Server not found

if [[ "$(does_server_exist)" == "false" ]]; then
    handle_error "Server not found."
fi



#### World already exists (when user passed as param) -- if not let it go, worker will handle blank param

if [[ "$NEW_WORLD" != "" ]]; then

    if [[ "$(does_world_exist $SERVER $NEW_WORLD)" == "true" ]]; then
        handle_error "World already exists."
    fi

fi



#### Server cannot be running

if [[ "$(is_server_running)" == "true" ]]; then
        handle_error "Server cannot be running."
fi







### RUN THE WORLD CREATOR WORKER ############

bash /usr/local/bin/gorpmc/worker/createworld.sh $1 $SERVER $NEW_WORLD || handle_error "Failed to run createworld.sh worker"