#!/usr/bin/env bash

### [ACTION: DELETE-SERVER] #######################################
#   Description:  Delete a server instsance
#   Parameters:   1: (required) Server directory name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################

# Copyright (C) Lance Nickel 2023.
# Distributed under GNU GPL v3.
# <https://gorp.lanickel.com/license/>



#### GUARDS ################

### KEY GUARD

if [[ "$1" == "pleasedontdothis" ]]; then
    OUTPUT=true
    ERRORS=true

elif [[ "$1" == "pleaseshutup" ]]; then
    OUTPUT=false
    ERRORS=true

elif [[ "$1" == "pleasebesilent" ]]; then
    OUTPUT=false
    ERRORS=false

else
    if $ERRORS; then echo "mcdeleteserver: Not intended to be run directly. Exit (13)."; fi
    exit 13
fi







#### SCRIPT PARAMETERS ################

source /usr/local/bin/gorpmc/worker/i_getconfigparams.sh

SERVER=$2







####







### PARAM RT-GUARD

if [[ "$SERVER" = "" ]]; then
    if $ERRORS; then echo "mcdeleteserver: Bad input. Expected: gorp delete-server [server-name]. Exit (14)."; fi
    exit 14
fi







### SERVER DIRECTORY RT-GUARD

if [[ -d "$HOMEDIR/servers/$SERVER" ]]; then
    cd $HOMEDIR/servers/$SERVER
else
    if $ERRORS; then echo "mcdeleteserver: Server not found. Exit (30)."; fi
    exit 30
fi







### SCREEN RT-GUARD

if [[ $(screen -ls | grep "$SERVER")  != "" ]]; then
        if $ERRORS; then echo "mcdeleteserver: Server cannot be running. Exit (34)."; fi
        exit 34
fi







### RUN DELETE WORKER

/usr/local/bin/gorpmc/worker/deleteserver.sh $1 $SERVER