#!/usr/bin/env bash

### [MCDELETEWORLD] ###############################################
#   Description:  Action script to setup world delete worker.
#   Parameters:   1: (required) Server directory name
#                 2: (optional) World (level) name for directory

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################



# PERMISSIONS GUARD

if [[ "$EUID" != 0 ]]; then
    echo "mcdeleteworld: Insufficient privilege. Exiting."
    exit
fi



# SCRIPT VARIABLES

SERVER=$1
WORLD_TO_DELETE=$2



####



# PARAM GUARD

if [ "$SERVER" = "" ]; then
    echo "mcdeleteworld: Server name missing. Expected command format: 'gorp delete-world [server-name] <world-name>'"
    exit
fi



# SERVER DIRECTORY GUARD

if [ -d "$HOMEDIR/servers/$SERVER" ]; then
    sleep 0.05
else
    echo "mcdeleteworld: Server doesn't exist. Exiting."
    exit
fi



# NO WORLDS GUARD

if [[ $(ls $HOMEDIR/servers/$SERVER/ | grep 'world') = "" ]]; then
    echo -e "mcdeleteworld: No worlds exist on this server instance.\nRun 'gorp create-world $SERVER [name]' to create a new world. Exiting."
    exit
fi



# SCREEN GUARD

if [[ $(screen -ls | grep "$SERVER")  != "" ]]; then
        echo "mcdeleteworld: Server '$SERVER' is running. Stop the server and then delete the world. Exiting."
        exit
fi



# WORLD DIRECTORY GUARD (when world name passed as param)

if [ "$WORLD_TO_DELETE" != "" ]; then

    if [ -d "$HOMEDIR/servers/$SERVER/world-$WORLD_TO_DELETE" ]; then
        sleep 0.005
    else
        echo "mcdeleteworld: A world with name '$WORLD_TO_DELETE' doesn't exist. Exiting."
        exit
    fi

fi



# RUN THE WORLD DELETE WORKER

/usr/local/bin/gorpmc/worker/deleteworld.sh $SERVER $WORLD_TO_DELETE