#!/usr/bin/env bash

### [ACTION: DELETE-WORLD] ########################################
#   Description:  Delete world files from a server instance.
#   Parameters:   1: (required) Server directory name
#                 2: (optional*) World (level) name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################

# Copyright (C) Lance Nickel 2023.
# Distributed under GNU GPL v3.
# <https://gorp.lanickel.com/license/>



#### GUARDS ################

### KEY GUARD

if [[ "$1" == "pleasedontdothis" ]]; then
    handle_error "Script not meant to be run directly."
fi







#### SCRIPT PARAMETERS ################

SERVER=$2
WORLD_TO_DELETE=$3







####







### PARAM RT-GUARD

if [[ "$SERVER" == "" ]]; then
    handle_error "Bad input. Expected: gorp delete-world [server-name] <world-name>."
fi







### SERVER DIRECTORY RT-GUARD

if [[ -d "$HOMEDIR/servers/$SERVER" ]]; then
    sleep 0.05
else
    handle_error "Server not found."
fi







### NO WORLDS RT-GUARD

if [[ $(ls $HOMEDIR/servers/$SERVER/ | grep 'world') == "" ]]; then
    handle_error -e "No worlds exist on this server."
fi







### SCREEN RT-GUARD

if [[ $(screen -ls | grep "$SERVER")  != "" ]]; then
        handle_error "Server cannot be running."
fi







### WORLD DIRECTORY RT-GUARD (when world name passed as param)

if [[ "$WORLD_TO_DELETE" != "" ]]; then

    if [ -d "$HOMEDIR/servers/$SERVER/world-$WORLD_TO_DELETE" ]; then
        sleep 0.005
    else
        handle_error "World not found."
    fi

fi







### RUN THE WORLD DELETE WORKER

source /usr/local/bin/gorpmc/worker/deleteworld.sh $1 $SERVER $WORLD_TO_DELETE || handle_error "Failed to run deleteworld.sh worker."