#!/usr/bin/env bash

### [ACTION: DELETE-SERVER] #######################################
#   Description:  Delete a server instsance
#   Parameters:   1: (required) Server directory name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################

# Copyright (C) Lance Nickel 2023.
# Distributed under GNU GPL v3.
# <https://gorp.lanickel.com/license/>



#### GUARDS ################

### KEY GUARD

if [[ "$1" == "pleasedontdothis" ]]; then
    handle_error "Script not meant to be run directly."
fi







#### SCRIPT PARAMETERS ################

SERVER=$2







####







### PARAM RT-GUARD

if [[ "$SERVER" = "" ]]; then
    handle_error "Bad input. Expected: gorp delete-server [server-name]."
fi







### SERVER DIRECTORY RT-GUARD

if [[ -d "$HOMEDIR/servers/$SERVER" ]]; then
    cd $HOMEDIR/servers/$SERVER
else
    handle_error "Server not found."
fi







### SCREEN RT-GUARD

if [[ $(screen -ls | grep "$SERVER")  != "" ]]; then
        handle_error "Server cannot be running."
fi







### RUN DELETE WORKER

/usr/local/bin/gorpmc/worker/deleteserver.sh $1 $SERVER