#!/usr/bin/env bash

### [ACTION: DELETE-WORLD] ########################################
#   Description:  Delete world files from a server instance.
#   Parameters:   1: (required) Server directory name
#                 2: (optional*) World (level) name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################

# Copyright (C) Lance Nickel 2023.
# Distributed under GNU GPL v3.
# <https://gorp.lanickel.com/license/>



#### SETUP ############

#### Globals

. /usr/local/bin/gorpmc/functions/exit.sh
. /usr/local/bin/gorpmc/functions/params.sh
. /usr/local/bin/gorpmc/functions/functions.sh



#### Key guard

if [[ "$1" != "pleasedontdothis" ]]; then
    handle_error "Script not meant to be run directly."
fi



#### Collect arguments & additional variables

SERVER=$2
WORLD_TO_DELETE=$3







####







#### GUARDS ############

#### Bad user input

if [[ "$SERVER" == "" ]]; then
    handle_error "Bad input. Expected: gorp delete-world [server-name] <world-name>"
fi



#### Server not found

if [[ "$(does_server_exist)" == "false" ]]; then
    handle_error "Server not found."
fi



#### No worlds on server

if [[ $(ls $HOMEDIR/servers/$SERVER/ | grep 'world') == "" ]]; then
    handle_error "No worlds exist on this server."
fi



#### Server cannot be running

if [[ "$(is_server_running)" == "true" ]]; then
        handle_error "Server cannot be running."
fi



#### World not found

if [[ "$WORLD_TO_DELETE" != "" ]]; then

    if [[ "$(does_world_exist $SERVER $WORLD_TO_DELETE)" == "false" ]]; then
        handle_error "World not found."
    fi

fi







#### RUN THE WORLD DELETE WORKER ############

bash /usr/local/bin/gorpmc/worker/deleteworld.sh $1 $SERVER $WORLD_TO_DELETE || handle_error "Failed to run deleteworld.sh worker"