#!/usr/bin/env bash

### [MCDELETESERVER] ##############################################
#   Description:  Action script to setup server delete worker.
#   Parameters:   1: (required) Server directory name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################



# PERMISSIONS GUARD

if [[ "$EUID" != 0 ]]; then
    echo "mcdelete: Insufficient privilege. Exiting."
    exit
fi



# SCRIPT VARIABLES

SERVER=$1



####



# PARAM GUARD

if [ "$SERVER" = "" ]; then
    echo "mcdelete: Please specify a server. Exiting"
    exit
fi



# SERVER DIRECTORY GUARD

if [ -d "/minecraft/servers/$SERVER" ]; then
    cd /minecraft/servers/$SERVER
else
    echo "mcdelete: Specified server doesn't exist. Exiting."
    exit
fi



# SCREEN GUARD

if [[ $(screen -ls | grep "$SERVER")  != "" ]]; then
        echo "mcdelete: Server '$SERVER' is still running. Please stop the server first. Exiting."
        exit
fi



# RUN DELETE WORKER

/bin/gorputils/worker/deleteserver.sh $SERVER