#!/usr/bin/env bash

### [ACTION: GET-JAR] #############################################
#   Description:  Action script to setup jar download worker.
#   Parameters:   None
#   Flags:        -v [version] | -u [url]

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################

# Copyright (C) Lance Nickel 2023.
# Distributed under GNU GPL v3.
# <https://gorp.lanickel.com/license/>



#### GUARDS ################

### KEY GUARD

if [[ "$1" == "pleasedontdothis" ]]; then
    handle_error "Script not meant to be run directly"
fi







#### SCRIPT OPTS ################

OPTIND=2
while getopts ":g:u:" flag; do
    case $flag in
        g)
            MODE="g"
            ARG="$OPTARG"
            ;;
        u)
            MODE="u"
            ARG="$OPTARG"
            ;;
        \?)
            handle_error "Bad input. Expected: gorp get-jar [-u | -v] [url | version]"
            ;;
        :)
            handle_error "Bad input. Expected: gorp get-jar [-u | -v] [url | version]"
            ;;
    esac
done
        
        






####







### PARAM RT-GUARD

if [[ "$MODE" == "" ]]; then
    handle_error "mcgetjar: Bad input. Expected: gorp get-jar [game-version]."
fi







### RUN JAR DOWNLOADER

source /usr/local/bin/gorpmc/worker/getjar.sh $1 "$MODE" "$ARG" || handle_error "Failed to run getjar.sh worker."