#!/usr/bin/env bash

### [ACTION: GET-JAR] #############################################
#   Description:  Action script to setup jar download worker.
#   Parameters:   None
#   Flags:        -v [version] | -u [url]

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################



#### GUARDS ################

### KEY GUARD

if [[ "$1" == "pleasedontdothis" ]]; then
    OUTPUT=true
    ERRORS=true

elif [[ "$1" == "pleaseshutup" ]]; then
    OUTPUT=false
    ERRORS=true

elif [[ "$1" == "pleasebesilent" ]]; then
    OUTPUT=false
    ERRORS=false

else
    if $ERRORS; then echo "mcgetjar: Not intended to be run directly. Exit (13)."; fi
    exit 13
fi







#### SCRIPT OPTS ################

OPTIND=2
while getopts ":u:v:" flag; do
    case $flag in
        u)
            MODE="u"
            ARG="$OPTARG"
            ;;
        v)
                MODE="v"
                ARG="$OPTARG"
                ;;
        \?)
            if $ERRORS; then echo "Bad input. Expected: gorp get-jar [-u | -v] [url | version]. Exit (14)."; fi
            exit 14
            ;;
        :)
            if $ERRORS; then echo "Bad input. Expected: gorp get-jar [-u | -v] [url | version]. Exit (14)."; fi
            exit 14
            ;;
    esac
done
        
        






####







### PARAM RT-GUARD

if [[ "$MODE" == "" ]]; then
    if $ERRORS; then echo "mcgetjar: Bad input. Expected: gorp get-jar [game-version]. Exit (14)."; fi
    exit 14
fi







### RUN JAR DOWNLOADER

/usr/local/bin/gorpmc/worker/getjar.sh $1 "$MODE" "$ARG"