#!/usr/bin/env bash

### [MCPOWER] #####################################################
#   Description:  Shut down all servers during a power outage
#   Parameters:   None

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##  This script is OVERWRITTEN any time a C.U.M. update is run.  ##
###################################################################



# PERMISSIONS GUARD

if [[ "$EUID" != 0 ]]; then
    echo "POWER OUTAGE SHUTDOWN: Insufficient privilege. Shutdown failed."
    exit
fi



####



# FOR EACH SERVER, RUN SHUTDOWN ACTION WITH POWER PARAM

for d in "/minecraft/servers/"*
do
        SERVER=$(echo $(basename "$d"))
        /bin/gorputils/action/mcstop $SERVER power
done