#!/usr/bin/env bash

### [MCPOWER] #####################################################
#   Description:  Action script that does mcstop action on all.
#   Parameters:   None

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################



#### GUARDS ################

### KEY GUARD

if [[ "$1" == "pleasedontdothis" ]]; then
    OUTPUT=true
    ERRORS=true

elif [[ "$1" == "pleaseshutup" ]]; then
    OUTPUT=false
    ERRORS=true

elif [[ "$1" == "pleasebesilent" ]]; then
    OUTPUT=false
    ERRORS=false

else
    if $ERRORS; then echo "mcpower: Not intended to be run directly. Exit (13)."; fi
    exit 13
fi







#### SCRIPT PARAMETERS ################

source /usr/local/bin/gorpmc/worker/i_getconfigparams.sh







####







# FOR EACH SERVER, RUN SHUTDOWN ACTION WITH POWER PARAM

for d in "$HOMEDIR/servers/"*
do
        SERVER=$(echo $(basename "$d"))
        /usr/local/bin/gorpmc/action/mcstop $1 $SERVER
done