#!/usr/bin/env bash

### [MCRESETWORLD] ################################################
#   Description:  Action script to setup world reset worker.
#   Parameters:   1: (required) Server directory name
#                 2: (optional) World (level) name for directory

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################



# PERMISSIONS GUARD

if [[ "$EUID" != 0 ]]; then
    echo "mcresetworld: Insufficient privilege. Exiting."
    exit
fi



# SCRIPT VARIABLES

SERVER=$1
WORLD_TO_DELETE=$2



####



# PARAM GUARD

if [ "$SERVER" = "" ]; then
    echo "mcresetworld: Server name missing. Expected command format: 'gorp reset-world [server-name]'"
    exit
fi



# SERVER DIRECTORY GUARD

if [ -d "$HOMEDIR/servers/$SERVER" ]; then
    sleep 0.05
else
    echo "mcresetworld: Server doesn't exist. Exiting."
    exit
fi



# NO WORLDS GUARD

if [[ $(ls $HOMEDIR/servers/$SERVER/ | grep 'world') = "" ]]; then
    echo -e "mcresetworld: No worlds exist on this server instance.\nRun 'gorp create-world $SERVER [name]' to create a new world. Exiting."
    exit
fi



# RUN THE WORLD DELETE WORKER

/usr/local/bin/gorpmc/worker/resetworld.sh $SERVER