#!/usr/bin/env bash

### [ACTION: RESET-WORLD] #########################################
#   Description:  Regenerate active world in a server instance.
#   Parameters:   1: (required) Server directory name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################

# Copyright (C) Lance Nickel 2023.
# Distributed under GNU GPL v3.
# <https://gorp.lanickel.com/license/>



#### GUARDS ################

### KEY GUARD

if [[ "$1" == "pleasedontdothis" ]]; then
    handle_error "Script not meant to be run directly."
fi







#### SCRIPT PARAMETERS ################

SERVER=$2






####







### PARAM GUARD

if [[ "$SERVER" == "" ]]; then
    if $ERRORS; then echo "mcresetworld: Bad input. Expected: gorp reset-world [server-name]. Exit (14)."; fi
    exit 14
fi







### SERVER DIRECTORY GUARD

if [[ -d "$HOMEDIR/servers/$SERVER" ]]; then
    sleep 0.05
else
    if $ERRORS; then echo "mcresetworld: Server not found. Exit (30)."; fi
    exit 30
fi







### NO WORLDS GUARD

if [[ $(ls $HOMEDIR/servers/$SERVER/ | grep 'world') == "" ]]; then
    if $ERRORS; then echo -e "mcresetworld: No worlds exist on this server. Exit (42)."; fi
    exit 42
fi







### RUN THE WORLD DELETE WORKER

/usr/local/bin/gorpmc/worker/resetworld.sh $1 $SERVER