#!/usr/bin/env bash

### [ACTION: RESTORE-WORLD] #######################################
#   Description:  Restore world's files from backup to server.
#   Parameters:   1: (required) Server directory name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################

# Copyright (C) Lance Nickel 2023.
# Distributed under GNU GPL v3.
# <https://gorp.lanickel.com/license/>



#### SETUP ############

#### Key guard

if [[ "$1" == "pleasedontdothis" ]]; then
    handle_error "Script not meant to be run directly."
fi



#### Globals

source /usr/local/bin/gorpmc/functions/exit.sh
source /usr/local/bin/gorpmc/functions/params.sh
source /usr/local/bin/gorpmc/functions/functions.sh



#### Collect arguments & additional variables

SERVER=$2







####







#### GUARDS ############

#### Bad user input

if [[ "$SERVER" == "" ]]; then
    handle_errors "Bad input. Expected: gorp restore-world [server-name]"
fi



#### Server has no backups to restore from

if [[ ! -d "$BACKUP_DEST/$SERVER" ]]; then
    handle_errors "Server has no backups to restore from"
fi



#### Server cannot be running

if [[ "$(is_server_running)" == "true" ]]; then
        handle_error "Server cannot be running."
fi







#### RUN RESTORE WORKER ############

bash /usr/local/bin/gorpmc/worker/restoreworld.sh $1 $SERVER || handle_error "Failed to run restoreworld.sh worker"