#!/usr/bin/env bash

### [MCRESTART] ###################################################
#   Description:  Action script to setup restart worker.
#   Parameters:   1: (required) Server directory name
#                 2: (optional) <fast, now>

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################



# PERMISSIONS GUARD

if [[ "$EUID" != 0 ]]; then
    echo "RESTART: Insufficient privilege. Restart failed."
    exit
fi



# SCRIPT VARIABLES

SERVER=$1
SPEED=$2



####



# PARAM GUARD

if [ "$SERVER" = "" ]; then
    echo "RESTART: Please specify a server"
    exit

elif [ "$SERVER" == 'fast' ] || [ "$SERVER" == 'now' ] || [ "$SERVER" == 'power' ]; then
    echo "RESTART: Malformed command. Expected form: 'mcstop <server> <argument>'"
    exit
fi



# SERVER DIRECTORY GUARD

if [ -d "/minecraft/servers/$SERVER" ]; then
    cd /minecraft/servers/$SERVER
else
    echo "RESTART: Specified server doesn't exist. Restart failed."
    exit
fi



# NO SCREEN GUARD

if [[ $(screen -ls | grep "$SERVER")  = "" ]]; then
        echo "RESTART: Screen '$SERVER' is not running. Seems '$SERVER' is already stopped."
        exit
fi



# RUN WORKERS BASED ON PASSED PARAMS

if [ -z "$SPEED" ]; then
    /bin/gorputils/worker/backup.sh $SERVER
    /bin/gorputils/worker/warning.sh $SERVER restart
    /bin/gorputils/worker/shutdown.sh $SERVER
    /bin/gorputils/worker/start.sh $SERVER

elif [ $SPEED == "fast" ]; then
    /bin/gorputils/worker/warning.sh $SERVER stop
    /bin/gorputils/worker/shutdown.sh $SERVER
    /bin/gorputils/worker/start.sh $SERVER

elif [ $SPEED == "now" ]; then
    /bin/gorputils/worker/shutdown.sh $SERVER
    /bin/gorputils/worker/start.sh $SERVER

else
    echo "RESTART: Invalid second parameter. Restart failed."
    exit
fi