#!/usr/bin/env bash

### [MCRESTORE] ###################################################
#   Description:  Action script to setup backup restore worker.
#   Parameters:   1: (required) Server directory name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################



# PERMISSIONS GUARD

if [[ "$EUID" != 0 ]]; then
        echo "mcrestore: Insufficient privilege. Exiting."
        exit
fi



# SCRIPT VARIABLES

SERVER=$1
BACKUP_DIR=$(cat /minecraft/gorp.conf | grep "^[^#;]" | grep 'DEST=' | cut -d '=' -f 2)



####



# PARAM GUARD

if [ "$SERVER" = "" ]; then
    echo "mcrestore: Please specify a server. Exiting."
    exit
fi



# SERVER DIRECTORY GUARD

if [ -d "$BACKUP_DIR/$SERVER" ]; then
    sleep 0.005
else
    echo "mcrestore: Specified server has no backups to restore from. Exiting."
    exit
fi



# SCREEN GUARD

if [[ $(screen -ls | grep "$SERVER")  != "" ]]; then
        echo "mcrestore: Server '$SERVER' is running. Stop the server and then perform a restore. Exiting."
        exit
fi



# RUN RESTORE WORKER

/bin/gorputils/worker/restore.sh $SERVER