#!/usr/bin/env bash

### [ACTION: RESET-WORLD] #########################################
#   Description:  Regenerate active world in a server instance.
#   Parameters:   1: (required) Server directory name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################

# Copyright (C) Lance Nickel 2025.
# Distributed under GNU GPL v3.
# <https://gorp.lanickel.com/license/>



#### SETUP ############

#### Globals

. /usr/local/bin/gorpmc/functions/exit.sh
. /usr/local/bin/gorpmc/functions/params.sh
. /usr/local/bin/gorpmc/functions/functions.sh



#### Key guard

if [[ "$1" != "pleasedontdothis" ]]; then
    handle_error "Script not meant to be run directly."
fi



#### Collect arguments & additional variables

SERVER=$2







####







#### GUARDS ############

#### Bad user input

if [[ "$SERVER" == "" ]]; then
    handle_error "Bad input. Expected: gorp reset-world [server-name]."
fi



#### Server not found

if [[ "$(does_server_exist $SERVER)" == "false" ]]; then
    handle_error "Server not found."
fi



#### No worlds on server

if [[ $(ls $HOMEDIR/servers/$SERVER/ | grep 'world') == "" ]]; then
    handle_error "No worlds exist on this server."
fi







#### RUN THE WORLD DELETE WORKER ############

bash /usr/local/bin/gorpmc/worker/resetworld.sh $1 $SERVER || handle_error "Failed to run resetworld.sh worker."