#!/usr/bin/env bash

### [ACTION: RESTORE-WORLD] #######################################
#   Description:  Restore world's files from backup to server.
#   Parameters:   1: (required) Server directory name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################

# Copyright (C) Lance Nickel 2025.
# Distributed under GNU GPL v3.
# <https://gorp.lanickel.com/license/>



#### SETUP ############

#### Globals

. /usr/local/bin/gorpmc/functions/exit.sh
. /usr/local/bin/gorpmc/functions/params.sh
. /usr/local/bin/gorpmc/functions/functions.sh



#### Key guard

if [[ "$1" != "pleasedontdothis" ]]; then
    handle_error "Script not meant to be run directly."
fi



#### Collect arguments & additional variables

SERVER=$2







####







#### GUARDS ############

#### Bad user input

if [[ "$SERVER" == "" ]]; then
    handle_errors "Bad input. Expected: gorp restore-world [server-name]."
fi



#### No backups found to restore from

if [[ -d "$BACKUP_DEST/worlds/$SERVER/" ]]; then
    if [[ "$(ls $BACKUP_DEST/worlds/$SERVER/)" == "" ]]; then
        handle_error "Server has no world backups to restore from."
    fi
else
    handle_error "Server has no world backups to restore from."
fi



#### Server cannot be running

if [[ "$(is_server_running $SERVER)" == "true" ]]; then
        handle_error "Server cannot be running."
fi







#### RUN RESTORE WORKER ############

bash /usr/local/bin/gorpmc/worker/restoreworld.sh $1 $SERVER || handle_error "Failed to run restoreworld.sh worker."