#!/usr/bin/env bash

### [MCRESTART] ###################################################
#   Description:  Action script to setup restart worker.
#   Parameters:   1: (required) Server directory name
#                 2: (optional) <fast, now>

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################



#### GUARDS ################

### KEY GUARD

if [[ "$1" != "pleasedontdothis" ]]; then
    echo "mcrestart: Not intended to be run directly. Exit (13)."
    exit 13
fi



#### SCRIPT PARAMETERS ################

SERVER=$2
SPEED=$3


####



# PARAM RT-GUARD

if [ "$SERVER" = "" ] || [ "$SERVER" == 'fast' ] || [ "$SERVER" == 'now' ] || [ "$SERVER" == 'power' ]; then
    echo "mcrestart: Bad input. Expected: gorp stop [server-name] <option>. Exit (14)."
    exit 14
fi



# SERVER DIRECTORY RT-GUARD

if [[ -d "$HOMEDIR/servers/$SERVER" ]]; then
    cd $HOMEDIR/servers/$SERVER
else
    echo "mcrestart: Server not found. Exit (30)."
    exit 30
fi



# NO SCREEN RT-GUARD

if [[ $(screen -ls | grep "$SERVER")  = "" ]]; then
        echo "mcrestart: Server not running. Exit (32)."
        exit 32
fi



# RUN WORKERS BASED ON PASSED PARAMS

if [[ -z "$SPEED" ]]; then
    /usr/local/bin/gorpmc/worker/backupworld.sh pleasedontdothis $SERVER
    /usr/local/bin/gorpmc/worker/warning.sh pleasedontdothis $SERVER restart
    /usr/local/bin/gorpmc/worker/shutdown.sh pleasedontdothis $SERVER
    /usr/local/bin/gorpmc/worker/start.sh pleasedontdothis $SERVER

elif [[ $SPEED == "fast" ]]; then
    /usr/local/bin/gorpmc/worker/warning.sh pleasedontdothis $SERVER stop
    /usr/local/bin/gorpmc/worker/shutdown.sh pleasedontdothis $SERVER
    /usr/local/bin/gorpmc/worker/start.sh pleasedontdothis $SERVER

elif [[ $SPEED == "now" ]]; then
    /usr/local/bin/gorpmc/worker/shutdown.sh pleasedontdothis $SERVER
    /usr/local/bin/gorpmc/worker/start.sh pleasedontdothis $SERVER
    
fi