#!/usr/bin/env bash

### [ACTION: RESTORE-SERVER] ######################################
#   Description:  Restore server instance's files from backup.
#   Parameters:   1: (required) Server directory name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################

# Copyright (C) Lance Nickel 2023.
# Distributed under GNU GPL v3.
# <https://gorp.lanickel.com/license/>



#### GUARDS ################

### KEY GUARD

if [[ "$1" == "pleasedontdothis" ]]; then
    handle_error "Script not meant to be run directly."
fi







#### SCRIPT PARAMETERS ################

SERVER=$2







####







### PARAM RT-GUARD

if [[ "$SERVER" == "" ]]; then
    if $ERRORS; then echo "mcrestoreserver: Bad input. Expected: gorp restore-world [server-name]. Exit (14)."; fi
    exit 14
fi







### SERVER BACKUP DIRECTORY RT-GUARD

if [[ -d "$BACKUP_DEST/$SERVER/server-backups/" ]]; then
    if [[ "$(ls $BACKUP_DEST/$SERVER/server-backups/)" == "" ]]; then
        if $ERRORS; then echo "mcrestoreserver: Server has no backups to restore from. Exit (54)."; fi
        exit 54
    fi
else
    if $ERRORS; then echo "mcrestoreserver: Server has no backups to restore from. Exit (54)."; fi
    exit 54
fi







### SCREEN RT-GUARD

if [[ $(screen -ls | grep "$SERVER") != "" ]]; then
        if $ERRORS; then echo "mcrestoreserver: Server cannot be running. Exit (34)."; fi
        exit 34
fi







### RUN RESTORE WORKER

/usr/local/bin/gorpmc/worker/restoreserver.sh $1 $SERVER