#!/usr/bin/env bash

### [ACTION: STATUS] ##############################################
#   Description:  Output JSON string of server status items.
#   Parameters:   1: (required) Server directory name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################

# Copyright (C) Lance Nickel 2023.
# Distributed under GNU GPL v3.
# <https://gorp.lanickel.com/license/>



#### GUARDS ################

### KEY GUARD

if [[ "$1" == "pleasedontdothis" ]]; then
    handle_error "Script not meant to be run directly."
fi







#### SCRIPT PARAMETERS ################

SERVER=$2



####







### PARAM RT-GUARD

if [[ "$SERVER" == "" ]]; then
    if $ERRORS; then echo "mcserverstatus: Bad input. Expected: gorp -s [server-name]. Exit (14)."; fi
    exit 14
fi







### SERVER DIRECTORY RT-GUARD

if [[ -d "$HOMEDIR/servers/$SERVER" ]]; then
    # we can continue
    sleep 0.005
else
    if $ERRORS; then echo "mcserverstatus: Server not found. Exit (30)."; fi
    exit 30
fi







### NEVER RUN BEFORE RT-GUARDS

# Server.properties has no world set
if [[ $(cat $HOMEDIR/servers/$SERVER/server.properties | grep 'level-name=' | cut -d '=' -f2) = "" ]]; then
    if $ERRORS; then echo "mcserverstatus: The server must be run at least once. Exit (38)."; fi
    exit 38
fi

# Server.properties only one line (default)
if [[ $(cat $HOMEDIR/servers/$SERVER/server.properties | wc -l) = "1" ]]; then
    if $ERRORS; then echo "mcserverstatus: The server must be run at least once. Exit (38)."; fi
    exit 38
fi







### RUN STATUS WORKER

/usr/local/bin/gorpmc/worker/serverstatus.sh $1 $SERVER