#!/usr/bin/env bash

### [ACTION: STATUS] ##############################################
#   Description:  Output JSON string of server status items.
#   Parameters:   1: (required) Server directory name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################

# Copyright (C) Lance Nickel 2023.
# Distributed under GNU GPL v3.
# <https://gorp.lanickel.com/license/>



#### GUARDS ################

### KEY GUARD

if [[ "$1" == "pleasedontdothis" ]]; then
    handle_error "Script not meant to be run directly"
fi







#### SCRIPT PARAMETERS ################

SERVER=$2



####







### PARAM RT-GUARD

if [[ "$SERVER" == "" ]]; then
    handle_error "Bad input. Expected: gorp -s [server-name]"
fi







### SERVER DIRECTORY RT-GUARD

if [[ -d "$HOMEDIR/servers/$SERVER" ]]; then
    # we can continue
    sleep 0.005
else
    handle_error "Server not found"
fi







### NEVER RUN BEFORE RT-GUARDS

# Server.properties has no world set
if [[ $(cat $HOMEDIR/servers/$SERVER/server.properties | grep 'level-name=' | cut -d '=' -f2) = "" ]]; then
    handle_error "The server must be run at least once"
fi

# Server.properties only one line (default)
if [[ $(cat $HOMEDIR/servers/$SERVER/server.properties | wc -l) = "1" ]]; then
    handle_error "The server must be run at least once"
fi







### RUN STATUS WORKER

bash /usr/local/bin/gorpmc/worker/serverstatus.sh $1 $SERVER || handle_error "Failed to run serverstatus.sh worker"