#!/usr/bin/env bash

### [MCSTOP] ######################################################
#   Description:  Action script to setup a shutdown worker.
#   Parameters:   1: (required) Server directory name
#                 2: (optional) <fast, now, power>

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################



#### GUARDS ################

### KEY GUARD

if [[ "$1" != "pleasedontdothis" ]]; then
    echo "mcstop: Not intended to be run directly. Exit (13)."
    exit 13
fi



#### SCRIPT PARAMETERS ################

source /usr/local/bin/gorpmc/worker/i_getconfigparams.sh

SERVER=$2
ARG=$3



####



# PARAM RT-GUARD

if [ "$SERVER" = "" ] || [ "$SERVER" == 'fast' ] || [ "$SERVER" == 'now' ] || [ "$SERVER" == 'power' ]; then
    echo "mcstop: Bad input. Expected: gorp stop [server-name] <option>. Exit (14)."
    exit
fi



# SERVER DIRECTORY RT-GUARD

if [[ -d "$HOMEDIR/servers/$SERVER" ]]; then
    cd $HOMEDIR/servers/$SERVER
else
    echo "mcstop: Server not found. Exit (30)."
    exit 30
fi



# NO SCREEN RT-GUARD
if [[ $(screen -ls | grep "$SERVER")  = "" ]]; then
        echo "mcstop: Server not running. Exit (32)."
        exit 32
fi



# RUN WORKERS BASED ON PASSED PARAMS

if [[ -z "$ARG" ]]; then
    /usr/local/bin/gorpmc/worker/backupworld.sh pleasedontdothis $SERVER
    /usr/local/bin/gorpmc/worker/warning.sh pleasedontdothis $SERVER stop
    /usr/local/bin/gorpmc/worker/shutdown.sh pleasedontdothis $SERVER

elif [[ $ARG == "power" ]]; then
    /usr/local/bin/gorpmc/worker/warning.sh pleasedontdothis $SERVER power
    /usr/local/bin/gorpmc/worker/shutdown.sh pleasedontdothis $SERVER

elif [[ $ARG == "fast" ]]; then
    /usr/local/bin/gorpmc/worker/warning.sh pleasedontdothis $SERVER stop
    /usr/local/bin/gorpmc/worker/shutdown.sh pleasedontdothis $SERVER

elif [[ $ARG == "now" ]]; then
    /usr/local/bin/gorpmc/worker/shutdown.sh pleasedontdothis $SERVER

fi