#!/usr/bin/env bash

### [MCSTOP] ######################################################
#   Description:  Action script to setup a shutdown worker.
#   Parameters:   1: (required) Server directory name
#                 2: (optional) <fast, now, power>

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################



#### GUARDS ################

### KEY GUARD

if [[ "$1" != "pleasedontdothis" ]]; then
    echo "mcstop: Not intended to be run directly. Exit (13)."
    exit 13
fi







#### SCRIPT PARAMETERS ################

source /usr/local/bin/gorpmc/worker/i_getconfigparams.sh

SERVER=$2
MODE="normal"

OPTIND=2
while getopts ":*" flag; do
    case $flag in
        \?)
            echo "Bad input. Expected: gorp stop [server] [-f|n|v]. Exit (14)."
            exit 14
            ;;
    esac
done

OPTIND=3
while getopts ":fnv" flag; do
    case $flag in
        f)
            MODE="f"
            ;;
        n)
            MODE="n"
            ;;
        v)
            VERBOSE="v"
            ;;
    esac
done







####







### PARAM RT-GUARD

if [[ "$SERVER" = "" ]] || [[ "$SERVER" == "fast" ]] || [[ "$SERVER" == "now" ]] || [[ "$SERVER" == "power" ]]; then
    echo "mcstop: Bad input. Expected: gorp stop [server] [-f|n|v]. Exit (14)."
    exit
fi

if [[ "$MODE" == "fast" ]] || [[ "$MODE" == "now" ]] || [[ "$MODE" == "power" ]]; then
    echo "This command was updated in 1.4.0. See below for the new syntax:"
    echo "mcstop: Bad input. Expected: gorp stop [server] [-f|n|v]. Exit (14)."
    exit
fi







### SERVER DIRECTORY RT-GUARD

if [[ -d "$HOMEDIR/servers/$SERVER" ]]; then
    cd $HOMEDIR/servers/$SERVER
else
    echo "mcstop: Server not found. Exit (30)."
    exit 30
fi







### NO SCREEN RT-GUARD
if [[ $(screen -ls | grep "$SERVER") == "" ]]; then
        echo "mcstop: Server not running. Exit (32)."
        exit 32
fi







### RUN WORKERS BASED ON PASSED PARAMS

if [[ "$MODE" == "normal" ]]; then
    /usr/local/bin/gorpmc/worker/backupworld.sh pleasedontdothis $SERVER
    /usr/local/bin/gorpmc/worker/warning.sh pleasedontdothis "shut down"
    /usr/local/bin/gorpmc/worker/shutdown.sh pleasedontdothis $SERVER $VERBOSE
fi

if [[ "$MODE" == "f" ]]; then
    /usr/local/bin/gorpmc/worker/warning.sh pleasedontdothis "shut down"
    /usr/local/bin/gorpmc/worker/shutdown.sh pleasedontdothis $SERVER $VERBOSE
fi

if [[ "$MODE" == "n" ]]; then
    /usr/local/bin/gorpmc/worker/shutdown.sh pleasedontdothis $SERVER $VERBOSE
fi