#!/usr/bin/env bash

### [ACTION: START] ###############################################
#   Description:  Start a server instance.
#   Parameters:   1: (required) Server directory name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################



#### GUARDS ################

### KEY GUARD

if [[ "$1" == "pleasedontdothis" ]]; then
    OUTPUT=true
    ERRORS=true

elif [[ "$1" == "pleaseshutup" ]]; then
    OUTPUT=false
    ERRORS=true

elif [[ "$1" == "pleasebesilent" ]]; then
    OUTPUT=false
    ERRORS=false

else
    if $ERRORS; then echo "mcstart: Not intended to be run directly. Exit (13)."; fi
    exit 13
fi







#### SCRIPT PARAMETERS ################

source /usr/local/bin/gorpmc/worker/i_getconfigparams.sh

SERVER=$2
GENERATE=$3







####







### PARAM GUARD

if [[ "$SERVER" == "" ]]; then
    if $ERRORS; then echo "mcstart: Bad input. Expected: gorp start [server-name]. Exit (14)."; fi
    exit 14
fi







### GET ADDITIONAL SERVER INFO

SERVER_EXISTS=$(serverExists "$SERVER")
SERVER_RUNNING=$(serverRunning "$SERVER")







### SERVER DIRECTORY GUARD

if [[ $SERVER_EXISTS == "true" ]]; then
    cd $HOMEDIR/servers/$SERVER
else
    if $ERRORS; then echo "mcstart: Server not found. Exit (30)."; fi
    exit 30
fi







### SCREEN GUARD

if [[ "$SERVER_RUNNING" == "true" ]]; then
        if $ERRORS; then echo "mcstart: Server already running. Exit (33)."; fi
        exit 33
fi








### RUN STARTUP WORKER

/usr/local/bin/gorpmc/worker/start.sh $1 $SERVER $GENERATE