#!/usr/bin/env bash

### [MCSTART] #####################################################
#   Description:  Action script to setup startup worker.
#   Parameters:   1: (required) Server directory name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################



#### GUARDS ################

### KEY GUARD

if [[ "$1" != "pleasedontdothis" ]]; then
    echo "mcstart: Not intended to be run directly. Exit (13)."
    exit 13
fi



#### SCRIPT PARAMETERS ################

SERVER=$2



####



# PARAM GUARD

if [[ "$SERVER" = "" ]]; then
    echo "mcstart: Bad input. Expected: gorp start [server-name]. Exit (14)."
    exit 14
fi



# SERVER DIRECTORY GUARD

if [[ -d "$HOMEDIR/servers/$SERVER" ]]; then
    cd $HOMEDIR/servers/$SERVER
else
    echo "mcstart: Server not found. Exit (30)."
    exit 30
fi



# SCREEN GUARD

if [[ $(screen -ls | grep "$SERVER")  != "" ]]; then
        echo "mcstart: Server already running. Exit (33)."
        exit 33
fi



# RUN STARTUP WORKER

/usr/local/bin/gorpmc/worker/start.sh pleasedontdothis $SERVER