#!/usr/bin/env bash

### [ACTION: START] ###############################################
#   Description:  Start a server instance.
#   Parameters:   1: (required) Server directory name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################

# Copyright (C) Lance Nickel 2023.
# Distributed under GNU GPL v3.
# <https://gorp.lanickel.com/license/>



#### GUARDS ################

### KEY GUARD

if [[ "$1" == "pleasedontdothis" ]]; then
    handle_error "Script not meant to be run directly"
fi







#### SCRIPT PARAMETERS ################

SERVER=$2
GENERATE=$3







####







### PARAM GUARD

if [[ "$SERVER" == "" ]]; then
    handle_error "Bad input. Expected: gorp start [server-name]"
fi







### GET ADDITIONAL SERVER INFO

SERVER_EXISTS=$(serverExists "$SERVER")
SERVER_RUNNING=$(serverRunning "$SERVER")







### SERVER DIRECTORY GUARD

if [[ $SERVER_EXISTS == "true" ]]; then
    cd $HOMEDIR/servers/$SERVER
else
    handle_error "Server not found"
fi







### SCREEN GUARD

if [[ "$SERVER_RUNNING" == "true" ]]; then
        handle_error "Server already running"
fi








### RUN STARTUP WORKER

source /usr/local/bin/gorpmc/worker/start.sh $1 $SERVER $GENERATE || handle_error "Failed to run start.sh worker"