#!/usr/bin/env bash

### [MCSWITCHWORLD] ###############################################
#   Description:  Action script to setup world switch worker.
#   Parameters:   1: (required) Server directory name
#                 2: (optional) Server world name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################



#### GUARDS ################

### KEY GUARD

if [[ "$1" != "pleasedontdothis" ]]; then
    echo "mcswitchworld: Not intended to be run directly. Exit (13)."
    exit 13
fi



#### SCRIPT PARAMETERS ################

SERVER=$2
SWITCH_TO=$3
HOMEDIR=$(getHomedir)



####



# PARAM RT-GUARD

if [ "$SERVER" = "" ]; then
    echo "mcswitchworld: Bad input. Expected: gorp switch-world [server-name] <world-name>. Exit (14)."
    exit 14
fi



# SERVER DIRECTORY RT-GUARD

if [ -d "$HOMEDIR/servers/$SERVER" ]; then
    sleep 0.05
else
    echo "mcswitchworld: Server not found. Exit (30)."
    exit 30
fi



# NO WORLDS RT-GUARD

if [[ $(ls $HOMEDIR/servers/$SERVER/ | grep 'world') = "" ]]; then
    echo "mcswitchworld: No worlds exist on this server. Exit (42)."
    exit
fi



# WORLD DOESN'T EXIST RT-GUARD (when world name passed as param)

if [ "$SWITCH_TO" != "" ]; then

    if [ -d "$HOMEDIR/servers/$SERVER/world-$SWITCH_TO" ]; then
        sleep 0.005
    else
        echo "mcswitchworld: World not found. Exit (40)."
        exit 40
    fi

fi



# SCREEN RT-GUARD

if [[ $(screen -ls | grep "$SERVER")  != "" ]]; then
        echo "mcswitchworld: Server cannot be running. Exit (34)."
        exit 34
fi



# RUN THE WORLD CREATOR WORKER

/usr/local/bin/gorpmc/worker/switchworld.sh pleasedontdothis $SERVER $SWITCH_TO