#!/usr/bin/env bash

### [ACTION: SWITCH-WORLD] ########################################
#   Description:  Switch a server instance's active world
#   Parameters:   1: (required) Server directory name
#                 2: (optional*) World (level) name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################



#### GUARDS ################

### KEY GUARD

if [[ "$1" == "pleasedontdothis" ]]; then
    OUTPUT=true
    ERRORS=true

elif [[ "$1" == "pleaseshutup" ]]; then
    OUTPUT=false
    ERRORS=true

elif [[ "$1" == "pleasebesilent" ]]; then
    OUTPUT=false
    ERRORS=false

else
    if $ERRORS; then echo "mcswitchworld: Not intended to be run directly. Exit (13)."; fi
    exit 13
fi







#### SCRIPT PARAMETERS ################

source /usr/local/bin/gorpmc/worker/i_getconfigparams.sh

SERVER=$2
SWITCH_TO=$3







####







### PARAM RT-GUARD

if [[ "$SERVER" = "" ]]; then
    if $ERRORS; then echo "mcswitchworld: Bad input. Expected: gorp switch-world [server-name] <world-name>. Exit (14)."; fi
    exit 14
fi







### SERVER DIRECTORY RT-GUARD

if [[ -d "$HOMEDIR/servers/$SERVER" ]]; then
    sleep 0.05
else
    if $ERRORS; then echo "mcswitchworld: Server not found. Exit (30)."; fi
    exit 30
fi







### NO WORLDS RT-GUARD

if [[ $(ls $HOMEDIR/servers/$SERVER/ | grep 'world') == "" ]]; then
    if $ERRORS; then echo "mcswitchworld: No worlds exist on this server. Exit (42)."; fi
    exit
fi







### WORLD DOESN'T EXIST RT-GUARD (when world name passed as param)

if [[ "$SWITCH_TO" != "" ]]; then

    if [[ -d "$HOMEDIR/servers/$SERVER/world-$SWITCH_TO" ]]; then
        sleep 0.005
    else
        if $ERRORS; then echo "mcswitchworld: World not found. Exit (40)."; fi
        exit 40
    fi

fi







### SCREEN RT-GUARD

if [[ $(screen -ls | grep "$SERVER")  != "" ]]; then
        if $ERRORS; then echo "mcswitchworld: Server cannot be running. Exit (34)."; fi
        exit 34
fi







### RUN THE WORLD CREATOR WORKER

/usr/local/bin/gorpmc/worker/switchworld.sh $1 $SERVER $SWITCH_TO