#!/usr/bin/env bash

### [ACTION: SWITCH-WORLD] ########################################
#   Description:  Switch a server instance's active world
#   Parameters:   1: (required) Server directory name
#                 2: (optional*) World (level) name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################

# Copyright (C) Lance Nickel 2023.
# Distributed under GNU GPL v3.
# <https://gorp.lanickel.com/license/>



#### SETUP ############

#### Globals

. /usr/local/bin/gorpmc/functions/exit.sh
. /usr/local/bin/gorpmc/functions/params.sh
. /usr/local/bin/gorpmc/functions/functions.sh



#### Key guard

if [[ "$1" != "pleasedontdothis" ]]; then
    handle_error "Script not meant to be run directly."
fi



#### Collect arguments & additional variables

SERVER=$2
SWITCH_TO=$3







####







#### GUARDS ############

#### Bad user input

if [[ "$SERVER" = "" ]]; then
    handle_error "Bad input. Expected: gorp switch-world [server-name] <world-name>."
fi



#### Server not found

if [[ "$(does_server_exist $SERVER)" == "false" ]]; then
    handle_error "Server not found."
fi



#### No worlds on server

if [[ $(ls $HOMEDIR/servers/$SERVER/ | grep 'world') == "" ]]; then
    handle_error "No worlds exist on this server."
fi



#### World doesn't exist (when passed by user, if not worker will handle this)

if [[ "$SWITCH_TO" != "" ]]; then
    if [[ ! -d "$HOMEDIR/servers/$SERVER/world-$SWITCH_TO" ]]; then
        handle_error "World not found."
    fi
fi



#### Server cannot be running

if [[ "$(is_server_running $SERVER)" == "true" ]]; then
        handle_error "Server cannot be running."
fi







#### RUN THE WORLD CREATOR WORKER ############

bash /usr/local/bin/gorpmc/worker/switchworld.sh $1 $SERVER $SWITCH_TO || handle_error "Failed to run switchworld.sh worker."