#!/usr/bin/env bash

### [MCUPDATE] ####################################################
#   Description:  User-frontend script to get latest server JAR.
#   Parameters:   None

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##  This script is OVERWRITTEN any time a C.U.M. update is run.  ##
###################################################################



# PERMISSIONS GUARD

if [[ "$EUID" != 0 ]]; then
    echo "UPDATE: Insufficient privilege. Update failed."
    exit
fi



####



# RUN UPDATE WORKER

/bin/gorputils/worker/update.sh