#!/usr/bin/env bash

### [MCUPDATE] ####################################################
#   Description:  Action script to setup update worker.
#   Parameters:   None

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################



# PERMISSIONS GUARD

if [[ "$EUID" != 0 ]]; then
    echo "mcupdate: Insufficient priviliege. Exiting."
    exit
fi



####



# RUN UPDATE WORKER

/usr/local/bin/gorputils/worker/updatejar.sh $VERSION