#!/usr/bin/env bash

### [ACTION: UPDATE-JAR] ##########################################
#   Description:  Download and install the latest stable Paper JAR.
#   Parameters:   None

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################

# Copyright (C) Lance Nickel 2023.
# Distributed under GNU GPL v3.
# <https://gorp.lanickel.com/license/>



#### GUARDS ################

### KEY GUARD

if [[ "$1" == "pleasedontdothis" ]]; then
    handle_error "Script not meant to be run directly"
fi







####







### RUN UPDATE WORKER

source /usr/local/bin/gorpmc/worker/updatejar.sh $1 $VERSION || handle_error "Failed to run updatejar.sh worker"