#!/usr/bin/env bash

### [GORP] ########################################################
#   Description:  Main Gorp launcher.
#   Parameters:   1: (required) Action <backup, update, create, delete, power, start, stop, restart, help, upgrade>
#                 2: (required) Server name
#                 3: (optional) Argument <fast, now, power>

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##   This script is OVERWRITTEN any time a Gorp update is run.   ##
###################################################################



# SCRIPT VARIABLES

ACTION=$1
ARG1=$2
ARG2=$3



####



if [ $ACTION = "backup" ]; then
    /bin/gorputils/action/mcbackup $ARG1

elif [ $ACTION = "restore" ]; then
    /bin/gorputils/action/mcrestore $ARG1

elif [ $ACTION = "update" ]; then
    /bin/gorputils/action/mcupdate $ARG1

elif [ $ACTION = "get-jar" ]; then
    /bin/gorputils/action/mcgetjar $ARG1

elif [ $ACTION = "create-server" ]; then
    /bin/gorputils/action/mccreateserver $ARG1

elif [ $ACTION = "delete-server" ]; then
    /bin/gorputils/action/mcdeleteserver $ARG1

elif [ $ACTION = "create-world" ]; then
    /bin/gorputils/action/mccreateworld $ARG1 $ARG2

elif [ $ACTION = "delete-world" ]; then
    /bin/gorputils/action/mcdeleteworld $ARG1 $ARG2

elif [ $ACTION = "switch-world" ]; then
    /bin/gorputils/action/mcswitchworld $ARG1

elif [ $ACTION = "power" ]; then
    /bin/gorputils/action/mcpower

elif [ $ACTION = "start" ]; then
    /bin/gorputils/action/mcstart $ARG1

elif [ $ACTION = "stop" ]; then
    /bin/gorputils/action/mcstop $ARG1 $ARG2

elif [ $ACTION = "restart" ]; then
    /bin/gorputils/action/mcrestart $ARG1 $ARG2

elif [ $ACTION = "help" ]; then
    /bin/gorputils/action/gorphelp

elif [ $ACTION = "upgrade" ]; then
    /bin/gorputils/action/gorpupgrade

else
    echo "Invalid parameters. Use gorp help for more information."
fi