#!/usr/bin/env bash

### [MCRESTART] ###################################################
#   Description:  User-frontend script to restart a server.
#   Parameters:   1: (required) Server directory name
#                 2: (optional) <fast, now>

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##  This script is OVERWRITTEN any time a C.U.M. update is run.  ##
###################################################################



# PERMISSIONS GUARD

if [[ "$EUID" != 0 ]]; then
    echo "RESTART: Insufficient privilege. Restart failed."
    exit
fi



# SCRIPT VARIABLES

SERVER=$1
SPEED=$2



####



# SERVER DIRECTORY GUARD

if [ -d "/minecraft/servers/$SERVER" ]; then
    cd /minecraft/servers/$SERVER
else
    echo "RESTART: Specified server doesn't exist. Restart failed."
    exit
fi



# RUN WORKERS BASED ON PASSED PARAMS

if [ -z "$SPEED" ]; then
    /bin/mcutils/backup.sh $SERVER
    /bin/mcutils/warning.sh $SERVER restart
    /bin/mcutils/shutdown.sh $SERVER
    /bin/mcutils/start.sh $SERVER

elif [ $SPEED == "fast" ]; then
    /bin/mcutils/warning.sh $SERVER stop
    /bin/mcutils/shutdown.sh $SERVER
    /bin/mcutils/start.sh $SERVER

elif [ $SPEED == "now" ]; then
    /bin/mcutils/shutdown.sh $SERVER
    /bin/mcutils/start.sh $SERVER

else
    echo "RESTART: Invalid second parameter. Restart failed."
    exit
fi