#!/usr/bin/env bash

### [MCSTART] #####################################################
#   Description:  User-frontend script to start a server.
#   Parameters:   1: (required) Server directory name

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##  This script is OVERWRITTEN any time a C.U.M. update is run.  ##
###################################################################



# PERMISSIONS GUARD

if [[ "$EUID" != 0 ]]; then
        echo "STARTUP: Insufficient privilege. Startup failed."
        exit
fi



# SCRIPT VARIABLES

SERVER=$1



####



# SERVER DIRECTORY GUARD

if [ -d "/minecraft/servers/$SERVER" ]; then
    cd /minecraft/servers/$SERVER
else
    echo "STARTUP: Specified server doesn't exist. Startup failed."
    exit
fi



# RUN STARTUP WORKER

/bin/mcutils/start.sh $SERVER