#!/usr/bin/env bash

### [MCSTOP] ######################################################
#   Description:  User-frontend script to stop a server.
#   Parameters:   1: (required) Server directory name
#                 2: (optional) <fast, now, power>

############################ [WARNING] ############################
##    No part of this script is designed to be user-editable.    ##
##  This script is OVERWRITTEN any time a C.U.M. update is run.  ##
###################################################################



# PERMISSION GUARD

if [[ "$EUID" != 0 ]]; then
    echo "SHUTDOWN: Insufficient privilege. Shutdown failed."
    exit
fi



# SCRIPT VARIABLES

SERVER=$1
ARG=$2



####



# PARAM GUARD

if [ "$SERVER" = "" ]; then
    echo "SHUTDOWN: Please specify a server"
    exit

elif [ "$SERVER" == 'fast' ] || [ "$SERVER" == 'now' ] || [ "$SERVER" == 'power' ]; then
    echo "SHUTDOWN: Malformed command. Expected form: 'mcstop <server> <argument>'"
    exit
fi



# SERVER DIRECTORY GUARD

if [ -d "/minecraft/servers/$SERVER" ]; then
    cd /minecraft/servers/$SERVER
else
    echo "SHUTDOWN: Specified server doesn't exist. Shutdown failed."
    exit
fi



# NO SCREEN GUARD
if [[ $(screen -ls | grep "$SERVER")  = "" ]]; then
        echo "SHUTDOWN: Screen '$SERVER' is not running. Seems '$SERVER' is already stopped."
        exit
fi



# RUN WORKERS BASED ON PASSED PARAMS

if [ -z "$ARG" ]; then
    /bin/mcutils/backup.sh $SERVER
    /bin/mcutils/warning.sh $SERVER stop
    /bin/mcutils/shutdown.sh $SERVER

elif [ $ARG == "power" ]; then
    /bin/mcutils/warning.sh $SERVER power
    /bin/mcutils/shutdown.sh $SERVER

elif [ $ARG == "fast" ]; then
    /bin/mcutils/warning.sh $SERVER stop
    /bin/mcutils/shutdown.sh $SERVER

elif [ $ARG == "now" ]; then
    /bin/mcutils/shutdown.sh $SERVER

else
    echo "SHUTDOWN: Invalid second parameter. Shutdown failed."
fi